name: book-stack
services:
  nginx:
    build:
      context: ./build/nginx
      dockerfile: Dockerfile
    depends_on:
      pgsql:
        condition: service_healthy
        restart: true
        required: true
      web:
        condition: service_started
        restart: true
        required: true
    image: kayrhancse/book-stack-nginx:latest
    networks:
      - web
    ports:
      - "80:80"
    pull_policy: always
  pgsql:
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - 'postgres'
      retries: 3
      timeout: 5s
    image: postgres:16.3-bookworm
    networks:
      - web
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./build/web/Dockerfile
    depends_on:
      pgsql:
        condition: service_healthy
        restart: true
        required: true
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html
    image: kayrhancse/book-stack-web:latest
    networks:
      - web
    ports:
      - "9000:80"
    pull_policy: always
networks:
  web:
    driver: bridge
volumes:
  db_data:
    driver: local
